header <- as.character(read.table("household_power_consumption.txt", sep = ";", nrows = 1, as.is = TRUE))
data <- read.table("household_power_consumption.txt", sep = ";", na.strings = "?", skip = 66637, nrows = 2880, col.names = header)
data$datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
png(file = "plot3.png")
plot(rep(data$datetime, 3), c(data$Sub_metering_1, data$Sub_metering_2, data$Sub_metering_3), type = "n", xlab = NA, ylab = "Energy sub metering")
lines(data$datetime, data$Sub_metering_1, col = "black")
lines(data$datetime, data$Sub_metering_2, col = "red")
lines(data$datetime, data$Sub_metering_3, col = "blue")
legend("topright", legend = header[7:9], col = c("black", "red", "blue"), lty = 1)
dev.off()