library(swirlify)
new_lesson("Lesson 1", "My First Course")
wq_message()
wq_command()
add_to_manifest()
test_lesson()
demo_lesson()
get_current_lesson()
new_lesson("Lesson 2", "My First Course")
wq_multiple()
add_to_manifest()
test_lesson()
demo_lesson()
wq_figure()
demo_lesson()
wq_figure()
demo_lesson()